version: "3.8"

services:
  database:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    volumes:
      - ./local-initdb.sql:/docker-entrypoint-initdb.d/local-initdb.sql
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  broker:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
